Menambahkan sidebar, menambahkan table karyawan
glints-IPE-4/frontend_staff_attendance pull request #1
Opened 2021-09-20 01:36 UTC by jember08

2021-09-20 06:03 UTC, LordAldi requested changes

2021-09-20 06:03 UTC, LordAldi commented on src/styles/Dashboardpage.scss
> +}
salah format nama, jadi importny gagal

2021-09-20 06:03 UTC, LordAldi commented on src/styles/index.scss
> +@import 'dashboardpage';
ini

2021-09-20 08:58 UTC, LordAldi commented on src/App.jsx
> +        <Route path='/DashboardPage' exact component={Layout(DashboardPage)} />
ini tolong ubah ke / aja gak usah /DashboardPage

2021-09-20 08:58 UTC, jember08 commented on src/App.jsx
> +        <Route path='/DashboardPage' exact component={Layout(DashboardPage)} />
wait

2021-09-20 09:18 UTC, LordAldi requested changes

2021-09-20 09:18 UTC, LordAldi commented on src/pages/DashboardPage.jsx
> +const DashboardPage = () => (
pisah" jadikan component masing"

2021-09-20 09:18 UTC, LordAldi commented on src/pages/DashboardPage.jsx
> +          <div className='status-staff'>Sakit</div>
tulisan warna putih

2021-09-20 09:18 UTC, LordAldi commented on src/pages/DashboardPage.jsx
> +        <div className='button'>
penamaan classny jgn button nanti malah ketuker dgn button yg bneran, misal button-group-.....

2021-09-20 09:18 UTC, LordAldi commented on src/styles/_dashboard.scss
> +        margin-left: 77px;
jgn diatur pke margin, pke flexbox

2021-09-20 09:18 UTC, LordAldi commented on .vscode/settings.json
> +}
hapus dong

2021-09-20 10:51 UTC, jember08 commented on src/styles/_dashboard.scss
> +        margin-left: 77px;
done

2021-09-20 10:51 UTC, jember08 commented on .vscode/settings.json
> +}
sumpah ini muncul sendiri bang, udah done

2021-09-20 10:53 UTC, jember08 commented on src/pages/DashboardPage.jsx
> +          <div className='status-staff'>Sakit</div>
done

2021-09-20 10:53 UTC, jember08 commented on src/pages/DashboardPage.jsx
> +        <div className='button'>
done

2021-09-20 18:46 UTC, jember08 commented on src/pages/DashboardPage.jsx
> +const DashboardPage = () => (
done

2021-09-21 07:46 UTC, LordAldi approved these changes
lgtm

2021-09-21 07:49 UTC, merged